# MemoryServer Config file
#
# Libfabric provider to be used by OpenFAM libfabric datapath operations; default is sockets.
# Other options are psm2/verbs.
provider: sockets

# Number of threads used for delayed free.
delayed_free_threads: 1 

# Atomic library threads count - default (0) indicates ATL disabled
ATL_threads: 0 

# ATL queue size - Number of elements in each queue
ATL_queue_size: 1000

# ATL data size per thread(MiB) - This will be used to allocate buffers and other queue related
# data structures
ATL_data_size: 1024

# This option is to enable or disable resource relinquishment in FAM
# Value can be "enable" or "disable"
resource_release: enable

# Path where data item backups are placed.
# This path needs to be in a shared filesystem and accessible to  all memory servers.
# By default, the backup folder is created in a directory under directory mentioned 
# as part of environment variable OPENFAM_ROOT.
#fam_backup_path: /path-to-backup/

#Memory Server Attributes
#memory_type: memory type used in the memory server(persistent/volatile)
#fam_path : Path where data is stored.
#rpc_interface: Rpc address used by memory server to accept connections from Client Interface Service.
#libfabric port to be used for datapath operations.
#if_device: Interface used to connect to memory server(for eg: ib0,ib1).
Memservers:
 0:
   memory_type: volatile
   fam_path: /dev/shm/vol/
   rpc_interface: 127.0.0.1:8789
   libfabric_port: 7500
   if_device: eth0 

 1:
   memory_type: persistent
   fam_path: /dev/shm/per/
   rpc_interface: 127.0.0.1:8788
   libfabric_port: 7501
   if_device: eth1 
