# MemoryServer Config file
# Path where data is stored.
# By default NVMM default location will be selected (which by default is /dev/shm/<username>).
# fam_path: /dev/shm/username
#
# Rpc interface
# Rpc address used by memory server to accept connections from Client Interface Service.
#
# The Client Interface Service connect to this address if the memsrv_interface_type
# (defined in fam_client_interface_config.yaml) is rpc.
#Format:
#rpc_interface: <interface_address>:<portno>
# where interface address is hostname (fqdn)/ip4 address where grpc port should be exposed.
# portno is port to be used by OpenFAM for communication between Memory Server and
# Client Interface Service.
rpc_interface: 127.0.0.1:8789

# Libfabric provider to be used by OpenFAM libfabric datapath operations; default is sockets.
# Other options are psm2/verbs.
provider: sockets

#Libfabric port to be used for datapath operations.
libfabric_port: 7500

#Libfabric port to be used for datapath operations.
delayed_free_threads: 0 

# Atomic library threads count - default (0) indicates ATL disabled
ATL_threads: 0 

# ATL queue size - Number of elements in each queue
ATL_queue_size: 1000

# ATL data size per thread(MiB) - This will be used to allocate buffers and other queue related
# data structures
ATL_data_size: 1024
